apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-apps.fullname" . }}
  labels:
    {{- include "my-apps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30200
  selector:
    {{- include "my-apps.selectorLabels" . | nindent 4 }}
