- name: Pull and start docker image
  block:
    - name: Clear current repo
      include_tasks: 0-wipe.yml
      tags:
        - full_wipe_with_repo
      when: web_app_full_wipe == true

    - name: Pull docker image
      command: docker pull {{ repo_name }}:{{ version }}

    - name: Execute docker image
      command: docker run -d -p {{ inner_port }}:{{ app_port }} {{ repo_name }}:{{ version }} &

    - name: Render Docker Compose
      ansible.builtin.template:
          src: docker-compose.yml.j2
          dest: docker-compose.yml

    - name: docker-compose up
      shell: docker-compose up
  tags:
    - webserver