apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: web.apps.com
      http:
        paths:
          - path: /python-app
            pathType: Prefix
            backend:
              service:
                name: python-app-service
                port:
                  name: python-app-port
          - path: /rust-app
            pathType: Prefix
            backend:
              service:
                name: rust-app-service
                port:
                  name: rust-app-port